version: "3.8"

networks:
  demet2:
    driver: bridge

services:
  #--WEBSERVER--#
  webserver:
    build:
      context: ${demet2_PATH}/docker/apache
      args:
        - PHP_CONTAINER=${demet2_PREFIX}-php
    image: ${demet2_PREFIX}-webserver
    container_name: ${demet2_PREFIX}-webserver
    environment:
      - PHP_CONTAINER=${demet2_PREFIX}-php
    networks:
      - demet2
    ports:
      - ${HOST_PORT_WEBSERVER}:80
      - ${HOST_PORT_WEBSERVER_SSL}:440
    volumes:
      - ${demet2_PATH}/public:/var/www/html
      - ${demet2_PATH}/logs/webserver:/var/log/apache:rw${MOUNT_OPTIONS}
    depends_on:
      #--PHP83--#
      - php83
      #--/PHP83--#
  #--/WEBSERVER--#
  #--PHP83--#
  php83:
    build:
      context: ${demet2_PATH}/docker/php83
    image: ${demet2_PREFIX}-php
    container_name: ${demet2_PREFIX}-php
    networks:
      - demet2
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ${demet2_PATH}/public:/var/www/html
      #--MYSQL--#
    # depends_on:
    #   - mysql
      #--/MYSQL--#
  #--/PHP83--#
  #--MYSQL--#
#   mysql:
#     #--MARIADB-IMAGE--#
#     image: mariadb:${MARIADB_VERSION}
#     #--/MARIADB-IMAGE--#
#     container_name: ${demet2_PREFIX}-mysql
#     networks:
#       - demet2
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_DEFAULT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DEFAULT_DB}
#       MYSQL_USER: ${MYSQL_DEFAULT_USER}
#       MYSQL_PASSWORD: ${MYSQL_DEFAULT_PASSWORD}
#     ports:
#       - ${HOST_PORT_MYSQL}:3306
#     volumes:
#       - ${demet2_PATH}/docker/mysql/custom.cnf:/etc/mysql/conf.d/local.cnf
#       - ${demet2_PATH}/logs/mysql:/var/log/mysql:rw${MOUNT_OPTIONS}
#       - mysql-data:/var/lib/mysql
#   #--/MYSQL--#
#   #--PHPMYADMIN--#
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
#     container_name: ${demet2_PREFIX}-phpmyadmin
#     networks:
#       - demet2
#     depends_on:
#       #--PHP83--#
#       - php83
#       #--/PHP83--#
#       - mysql
#     ports:
#         - ${HOST_PORT_PHPMYADMIN}:80
#     environment:
#       MYSQL_USERNAME: ${MYSQL_DEFAULT_USER}
#       MYSQL_ROOT_PASSWORD: ${MYSQL_DEFAULT_PASSWORD}
#       PMA_HOST: mysql
#       PMA_PORT: ${HOST_PORT_MYSQL}
#   #--/PHPMYADMIN--#
# volumes:
#   demet2-data:
#     driver: "local"
#   #--MYSQL--#
#   mysql-data:
#     driver: "local"
#   #--/MYSQL--#
